### ISSUE TITLE
真机编绎提示图片找不到

### ISSUE THREAD

**Issue by breakind** [QMUI/QMUIDemo_iOS#1]
dyld: Library not loaded: @rpath/QMUIKit.framework/QMUIKit
  Referenced from: /var/containers/Bundle/Application/A77569E6-2BC0-4B8A-8B68-CE87E301F0F6/qmuidemo.app/qmuidemo
  Reason: image not found

Xcode 8.2.1  iPhone 6 10.1.1
模拟器正常运行

**Comment by MoLice** [comment]
请更新到最新的代码再尝试一下？

**Comment by breakind** [comment]
OK了
