### ISSUE TITLE
iOS11 Demo有点小问题

### ISSUE THREAD

**Issue by github410117** [QMUI/QMUIDemo_iOS#12]
### 运行环境 ###

- [x] iOS 设备：`模拟器`
- [x] 系统版本：`iOS 11`
- [x] Xcode 版本：`9`
- [x] QMUI iOS 版本：`1.x.x`

### 具体问题描述 ###
整体布局最下面偏移了！无法拉动上来
#### 问题截图 ####
![image](https://user-images.githubusercontent.com/15375736/27041903-f6408b1a-4fc7-11e7-90a4-e57617d411da.png)

**Comment by Winter-Yang** [comment]
iOS11应该修改scrollView相关的属性进行修改，目前我发现我的TableView 的contentSize向下偏移20pt，应该是针对iPhone8的处理，  
_scrollView.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever;

**Comment by MoLice** [comment]
已更新 Demo，请使用最新代码尝试。
