### ISSUE TITLE
Swift3.2如何像OC一样设置全局样式？

### ISSUE THREAD

**Issue by zenghaojim33** [QMUI/QMUIDemo_iOS#14]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 11`
- [x] Xcode 版本：`9`
- [x] QMUI iOS 版本：`2.0.0`

### 具体问题描述 ###

尝试使用QMUIConfiguration.sharedInstance()中的属性，不能生效。

**Comment by MoLice** [comment]
是否有按照[文档](http://qmuiteam.com/ios/page/start.html)的 **如何使用配置表** 操作？

**Comment by zenghaojim33** [comment]
桥接文件后使用配置表后生效了。不过貌似只要导入了QMUI，即使没有配置表，也会影响到原来的导航栏的barTintColor

**Comment by MoLice** [comment]
理论上应该不会的，配置表里的 navBarBarTintColor 默认值为 nil，当为 nil 时，QMUI 里是不会有代码去修改 navigationBar.barTintColor 的。

是否可以贴一些相关的代码、截图看看？例如你项目了是怎么设置 barTintColor 的、引入 QMUI 后被修改为什么。

**Comment by zenghaojim33** [comment]
<img width="1395" alt="wx20170922-145332 2x" src="https://user-images.githubusercontent.com/8848084/30732603-ee673f5a-9fa5-11e7-8e17-4711aa109dc4.png">
这个空工程中Storyboard中设置了barTintColor后运行，是能看到颜色被修改的，但是如果pod引入了QMUI则颜色变为默认的了。工程中没有一行代码。

**Comment by MoLice** [comment]
这应该是 QMUI 对 storyboard 的兼容有问题，已记录下来，后续的版本会修复这个问题，谢谢反馈。

**Comment by MoLice** [comment]
刚查了一下，为什么会出现这个问题，是因为引入配置表后，即便配置表里的 `navBarBarTintColor` 值默认为 `nil`，也会导致触发 [`QMUIConfiguration.m:232`](https://github.com/QMUI/QMUI_iOS/blob/master/QMUIKit/UICore/QMUIConfiguration.m#L232) 里修改 `UINavigationBar` appearance 的代码。而又因为对于 UIKit 而言，如果你在 storyboard 里修改某个 `UINavigationBar` 的 `barTintColor`，同时在项目里写了 `[UINavigationBar appearance].barTintColor = xxx`，那么代码会覆盖 storyboard 里的值（这一点与 QMUI 无关）。所以目前的解决方式是修改 `QMUIConfiguration.m`，如果走到这里时某些配置的值为 nil，则不继续执行，从而降低引入 QMUI 对项目的侵入性。

大概的修改代码示例如下，具体的要等下一个 Release 版本发布时才会带上。

```Objective-C
// QMUIConfiguration.m
- (void)setNavBarBarTintColor:(UIColor *)navBarBarTintColor {
    _navBarBarTintColor = navBarBarTintColor;
    if (navBarBarTintColor) {
        [UINavigationBar appearance].barTintColor = _navBarBarTintColor;
        [QMUIHelper visibleViewController].navigationController.navigationBar.barTintColor = _navBarBarTintColor;
    }
}
```
