### ISSUE TITLE
该工程无法在真机上运行起来

### ISSUE THREAD

**Issue by halfrisk** [QMUI/QMUIDemo_iOS#15]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.x.x`

### 具体问题描述 ###
之前的版本我都是可以运行起来，更新到最新后无法运行了
#### 问题截图 ####
![image](https://user-images.githubusercontent.com/19650796/39849971-969a68c8-5441-11e8-97fe-a97839f87187.png)

**Comment by MoLice** [comment]
自行解决证书问题。
