### ISSUE TITLE
非主线程操作

### ISSUE THREAD

**Issue by dqb101140127** [QMUI/QMUIDemo_iOS#17]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.x.x`

#### 问题截图 ####
![0b2ab99b-5445-44a3-b668-e6e5306a06a2](https://user-images.githubusercontent.com/13044675/43877112-c8c726b2-9bca-11e8-904f-b868d71879a6.png)

**Comment by MoLice** [comment]
与 #18 相同，这里的关键在于别人在主线程调用了这些方法，关键要看是谁触发的。

猜测你是用了系统的相片裁剪吧。
