### ISSUE TITLE
非主线程操作

### ISSUE THREAD

**Issue by dqb101140127** [QMUI/QMUIDemo_iOS#18]
![c7e1bfff-69b4-4f28-8dea-1421705f0882](https://user-images.githubusercontent.com/13044675/43877168-fd910b60-9bca-11e8-9d1a-a148ed0e563b.png)
![Uploading C7E1BFFF-69B4-4F28-8DEA-1421705F0882.png…]()

### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.x.x`

**Comment by MoLice** [comment]
需要完整的方法调用堆栈才能知道是哪里在非主线程调用了这个方法。
