### ISSUE TITLE
QMUISearchController例子无效

### ISSUE THREAD

**Issue by xilin** [QMUI/QMUIDemo_iOS#2]
进入子页面后点击列表无效
iOS 8.1 simulator

**Comment by MoLice** [comment]
这个例子主要是想展示 QMUISearchController 的使用，所以 cell 本身是没有加点击事件的。

**Comment by xilin** [comment]
![simulator screen shot 27 dec 2016 3 02 09 pm](https://cloud.githubusercontent.com/assets/543395/21493240/73e347d0-cc45-11e6-904c-597f03dc7925.png)
可是运行起来只是个普通的列表，并没有搜索功能？

**Comment by MoLice** [comment]
![image](https://cloud.githubusercontent.com/assets/1190261/21496702/6594c13e-cc5b-11e6-87c5-b1623df2687e.png)

应该要有一个搜索框在头部的，麻烦给一下你的 Xcode 版本、模拟器 iOS 版本。另外检查一下本地是否有修改过代码。

**Comment by xilin** [comment]
Xcode 8.2
模拟器是iOS 8.1 iPhone 6
本地没修改过代码，直接clone回来在的master分支上

**Comment by MoLice** [comment]
`QMUISearchController` 在 iOS 8 下，searchBar 默认大小为 `CGRectZero`，所以看不到，刚刚已经修复这个 bug，请更新代码重试，谢谢。

**Comment by xilin** [comment]
OK了~
