### ISSUE TITLE
UICollectionView+QMUICellSizeKeyCache暂时无法使用？ 

### ISSUE THREAD

**Issue by LH-Liu** [QMUI/QMUIDemo_iOS#20]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.x.x`

**Comment by MoLice** [comment]
对，遇到一些问题暂时无法解决。
