### ISSUE TITLE
真机运行报错

### ISSUE THREAD

**Issue by bloodspasm** [QMUI/QMUIDemo_iOS#22]
### 运行环境 ###

- [x] iOS 设备：`iPhone`
- [x] 系统版本：`iOS 12.x`
- [x] Xcode 版本：`10.x`
- [x] QMUI iOS 版本：`2.8.x`

### 具体问题描述 ###

无法真机运行报错

#### 问题截图 ####

<img width="426" alt="2018-11-01 5 35 02" src="https://user-images.githubusercontent.com/10420472/47844094-7b9a3180-ddfc-11e8-8247-9b1eb231541b.png">

**Comment by MoLice** [comment]
与项目无关
