### ISSUE TITLE
导航栏透明及导航栏透明度的修改

### ISSUE THREAD

**Issue by ywdonga** [QMUI/QMUIDemo_iOS#23]
### 运行环境 ###

- [x] iOS 设备：`iPhone8` 
- [x] 系统版本：`iOS 12.1.1`
- [x] Xcode 版本：`10.1`
- [x] QMUI iOS 版本：`2.9.1`

### 具体问题描述 ###
在部分界面需要做导航栏透明，使用返回透明图片的方法，发现没有效果
```
- (UIImage *)navigationBarShadowImage{
    return nil;
}
- (UIImage *)navigationBarBackgroundImage{
    return [UIImage qmui_imageWithColor:UIColorMakeWithRGBA(66, 66, 66, 0)];
}
```

是否能支持修改导航栏的透明度呢？

**Comment by MoLice** [comment]
`navigationBarBackgroundImage` 调用的地方在 UINavigationController+NavigationBarTransition.m:274，请自行打断点检查为什么没有走进去。

![image](https://user-images.githubusercontent.com/1190261/48469033-94f1a380-e828-11e8-8074-bd63f939e8af.png)

**Comment by ywdonga** [comment]
好的
