### ISSUE TITLE
Demo 点击拍摄视频崩溃了

### ISSUE THREAD

**Issue by chuansuozhongdelang** [QMUI/QMUIDemo_iOS#24]
### 运行环境 ###

- [x] iOS 设备：`iPhone xs` 
- [x] 系统版本：`iOS 12.1`
- [x] Xcode 版本：`10.1`
- [x] QMUI iOS 版本：`2.9.2`

### 具体问题描述 ###
Demo 点击QDSaveVideoToSpecifiedAlbumViewController类handleTakeVideoButtonClick方法拍摄视频崩溃了
#### 问题截图 ####
![3019147a-1868-474f-b21e-5c8b1b408891](https://user-images.githubusercontent.com/13161171/49215843-ae881300-f404-11e8-8ae9-7bd9203659bd.png)

**Comment by MoLice** [comment]
请查看你截图里 Xcode 控制台的 log，它已经说明了原因。如果不希望开启这个 NSAssert，请修改配置表 ShouldAssertResizableImageCapInsetsError 的值。
