### ISSUE TITLE
当 UISearchController isn't active，怎么实现 UISearchBar 的 icon and text 居中

### ISSUE THREAD

**Issue by weiminghuaa** [QMUI/QMUIDemo_iOS#26]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 12`
- [x] Xcode 版本：`10.1`
- [x] QMUI iOS 版本：`3.0.0`

### 具体问题描述 ###
我看到App Store的demo版本是居中的，但是github上运行的版本没找到可以居中的设置
#### 问题截图 ####
![img_1121](https://user-images.githubusercontent.com/2723525/50748675-80a0b480-1275-11e9-9937-7f365104dc98.PNG)
![img_1122](https://user-images.githubusercontent.com/2723525/50748677-81394b00-1275-11e9-8819-86655b661282.PNG)

**Comment by MoLice** [comment]
居中与否并非 QMUI 有意为之，是 iOS 不同的系统版本，UISearchBar 默认表现不一样。AppStore 的 QMUI 已经是很久以前的了，当时编译用的 SDK 版本，UISearchBar 还是居中的，现如今已经不一样了。

如果你仍需要强制改为居中，系统已经提供了对应方法，请参考 `UISearchBar -searchTextPositionAdjustment`、`UISearchBar -setPositionAdjustment:forSearchBarIcon:`，这些已不属于 QMUI 的范畴。

**Comment by weiminghuaa** [comment]
多谢解答！问题我先关了。我知道系统的这个API，但设置后，active变化过程中的动画很不协调自然，一直搞不定。
