### ISSUE TITLE
“关于”页面底部文字显示小bug

### ISSUE THREAD

**Issue by yubei1986** [QMUI/QMUIDemo_iOS#27]
### 运行环境 ###

- [x] iOS 设备：iPhone 5s
- [x] 系统版本：`iOS 9.2`
- [x] Xcode 版本：`10.1`
- [x] QMUI iOS 版本：`3.1.2`

### 具体问题描述 ###
关于里面的文字布局有问题，压住了上面的cell
#### 问题截图 ####
![image](https://user-images.githubusercontent.com/14355990/55061600-1eef2a00-50af-11e9-8830-d4c64fa07ef0.png)

**Comment by MoLice** [comment]
下个版本将会修复，感谢提醒。
![image](https://user-images.githubusercontent.com/1190261/55161332-42de6880-51a0-11e9-92ad-95ac77320059.png)
