### ISSUE TITLE
iPhone X 返回页面自动向上滚动

### ISSUE THREAD

**Issue by lengqingfeng** [QMUI/QMUIDemo_iOS#31]
### 运行环境 ###

- [x] iOS 设备：`iPhone`
- [x] 系统版本：`iOS 12.3.1`
- [x] Xcode 版本：`10.2.1`
- [x] QMUI iOS 版本：`3.2.1`

### 具体问题描述 ###
点击列表最下面的几个坑位进入后点击返回按钮后，页面自动向上滚动一段

**Comment by MoLice** [comment]
iOS 系统自身问题，暂时不处理。
