### ISSUE TITLE
framework not found LookinServer

### ISSUE THREAD

**Issue by XavierLost** [QMUI/QMUIDemo_iOS#33]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.x.x`

### 具体问题描述 ###
framework not found LookinServer?

**Comment by MoLice** [comment]
该 issue 因有用信息过少而被关闭，请补充信息后再 reopen。

**Comment by coderTong** [comment]
把工程文件夹放到左面 根路径, 所处的文件夹名不能有中文

**Comment by Qun-Bad-Boy** [comment]
> 把工程文件夹放到左面 根路径, 所处的文件夹名不能有中文

哈哈，你的方法果然有用，感谢
