### ISSUE TITLE
iOS版本你们用了YYImage和YYText这两个库吗？

### ISSUE THREAD

**Issue by inoryxun** [QMUI/QMUIDemo_iOS#34]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 12.4`
- [x] Xcode 版本：`10.3`
- [x] QMUI iOS 版本：`3.2.1`

### 具体问题描述 ###
目前两个库同时使用的话会报重复错误:Duplicate interface definition for class 'YYImage'
和这个错误
'CGRectApplyAffineTransformWithAnchorPoint' has different definitions in different modules; definition in module 'QMUIKit.QMUICommonDefines' first difference is function body

**Comment by MoLice** [comment]
QMUIKit、YYImage、YYText 这三个项目均为开源项目，理论上直接在 Xcode 里搜索相关代码即可知道是否有互相依赖、重复定义的问题。

建议自行排查自己项目对这三个开源项目的使用方式。
