### ISSUE TITLE
lookinserver.framework 不能打开

### ISSUE THREAD

**Issue by zidonJ** [QMUI/QMUIDemo_iOS#36]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.15`
- [x] Xcode 版本：`10.3`
- [x] QMUI iOS 版本：`4.0.0`

**Comment by hughkli** [comment]
请问“不能打开”是什么意思？这个 framework 是用来配合使用 Lookin 这款 mac app 的
