### ISSUE TITLE
4.0.0Demo模拟器运行出现framework not found LookinServer错误

### ISSUE THREAD

**Issue by yyks999** [QMUI/QMUIDemo_iOS#37]
### 运行环境 ###

- [x] iOS 设备：`iPhone` /  `模拟器`
- [x] 系统版本：`iOS 10.4.1`
- [x] Xcode 版本：`10.3`
- [x] QMUI iOS 版本：`4.0.0`

### 具体问题描述 ###
Xcode10.3模拟器运行Demo时，报错“framework not found LookinServer”，搜索关键词发现Other Linker Flags中有LookinServer的相关配置。

#### 问题截图 ####

![image](https://user-images.githubusercontent.com/4744650/64940076-a31fae80-d895-11e9-8df1-1f4a2fa0dbee.png)
![image](https://user-images.githubusercontent.com/4744650/64940101-b03c9d80-d895-11e9-87de-369faaeba93e.png)
![image](https://user-images.githubusercontent.com/4744650/64940109-b894d880-d895-11e9-935f-83c00008c803.png)

**Comment by lizhili42** [comment]
我也遇到了，我发现工程放在带有中文路径就会这样报错，放在纯英文路径下正常，可以尝试将工程放到其他目录下重新编译
