### ISSUE TITLE
关于在iOS13系统中报错'Client error attempting to change layout margins of a private view'

### ISSUE THREAD

**Issue by hurricane3807** [QMUI/QMUIDemo_iOS#38]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 13`
- [x] Xcode 版本：`11`
- [x] QMUI iOS 版本：`3.2.1`

### 具体问题描述 ###
 Assertion failure in -[_UINavigationBarContentView setDirectionalLayoutMargins:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKitCore/UIKit-3899.13.13/_UINavigationBarContentView.m:708
 *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Client error attempting to change layout margins of a private view'
#### 问题截图 ####
![image](https://user-images.githubusercontent.com/54128514/65369188-bf985e00-dc7c-11e9-984e-c79675795b29.png)

**Comment by baipeng1009472720** [comment]
我也遇到了这个问题。我本次暂时修改了代码 对iOS 13 兼容了一下，不执行这段代码。希望对你有所帮助。
```    
        NSString *version = [UIDevice currentDevice].systemVersion;
        float float_version = [version floatValue];
        if (float_version < 13 ) {
            ExtendImplementationOfVoidMethodWithoutArguments([UINavigationBar class], @selector(layoutSubviews), ^(UINavigationBar *selfObject) {
                UIView *contentView = selfObject.qmui_contentView;
                if (contentView) {
                    NSDirectionalEdgeInsets value = contentView.directionalLayoutMargins;
                    value.leading = value.trailing - (selfObject.qmui_customizingBackBarButtonItem ? 8 : 0);
                    contentView.directionalLayoutMargins = value;
                }
            });
        }
```

**Comment by MoLice** [comment]
https://github.com/Tencent/QMUI_iOS/issues/628

这里已有详述，请使用最新代码。
