### ISSUE TITLE
UIImage+QMUITheme文件报错

### ISSUE THREAD

**Issue by ghost** [QMUI/QMUIDemo_iOS#41]
### 运行环境 ###

- [x] iOS 设备：模拟器
- [x] 系统版本：iOS 12.4
- [x] Xcode 版本：Version 10.3 
- [x] QMUI iOS 版本：QMUIKit 4.0.2

### 具体问题描述 ###
UIImage+QMUITheme文件编译不通过
#### 问题截图 ####
![WeChatafe077bfec8f6bdf82a48d25a16b7d8a](https://user-images.githubusercontent.com/7418617/67187209-52631e80-f41c-11e9-840c-24c05a0b153b.png)

**Comment by MoLice** [comment]
4.0.2 主要针对 iOS 13，请使用 Xcode 11 编译。

参考 https://github.com/Tencent/QMUI_iOS/issues/764
