### ISSUE TITLE
您好 关于 修复使用 Xcode 11 编译到 iOS 9.0 上启动后会因为 Symbol not found

### ISSUE THREAD

**Issue by tengcoding** [QMUI/QMUIDemo_iOS#42]
### 运行环境 ###

- [x] iOS 设备：`模拟器`
- [x] 系统版本：`iOS 9.0`
- [x] Xcode 版本：`11.0`

### 具体问题描述 ###

您好 我目前出现了 使用xcode11编译 iOS9.0上会crash的问题  找了很多资料 也不知道应该怎么修复 ，无意中看到 你们第三方框架 资料上显示 修复了 这个问题  
"
修复使用 Xcode 11 编译到 iOS 9.0 上启动后会因为 Symbol not found: OBJC_CLASS$_PHLivePhotoRequestOptions 而 crash 的系统 bug。
"
想请教下 是如何修复的 

谢谢  ！

**Comment by MoLice** [comment]
你可以参考 [QMUIAsset.m:156-167](https://github.com/Tencent/QMUI_iOS/blob/master/QMUIKit/QMUIComponents/AssetLibrary/QMUIAsset.m#L156-L167)。

**Comment by tengcoding** [comment]
谢谢 后来我发现 把photo.framework  添加后设置为optional 也可以解决

**Comment by MoLice** [comment]
@tengcoding 确实，下个版本我们也会改为你说的方式，把之前的 NSClassFromString 去掉，谢谢！
