### ISSUE TITLE
在Xcode 11.2版本中出现关于QMUITextView崩溃的问题

### ISSUE THREAD

**Issue by hurricane3807** [QMUI/QMUIDemo_iOS#43]
### 运行环境 ###

- [x] iOS 设备：`iPhone``
- [x] 系统版本：`iOS 12.3`
- [x] Xcode 版本：`11.2`
- [x] QMUI iOS 版本：`4.0.2`

### 具体问题描述 ###
使用故事版或者XIB创建QMUITextView,编译运行时会崩溃，
Could not instantiate class named _UITextLayoutView because no class named _UITextLayoutView was found; the class needs to be defined in source code or linked in from a library (ensure the class is part of the correct target

#### 问题截图 ####
![image](https://user-images.githubusercontent.com/54128514/68186120-4bbcd580-ffde-11e9-8cba-d999a0c6986d.png)
![image](https://user-images.githubusercontent.com/54128514/68186389-fcc37000-ffde-11e9-9bca-deba994a2246.png)

**Comment by MoLice** [comment]
https://github.com/Tencent/QMUI_iOS/issues/799#issuecomment-549218259
