### ISSUE TITLE
首页的2个GridViewController进入下级演示页面再返回的时候，GridViewController总是往上抖动一下

### ISSUE THREAD

**Issue by qiu198022** [QMUI/QMUIDemo_iOS#44]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.x.x`

### 具体问题描述 ###
首页的2个GridViewController QMUIkit和Component往下滑动一点，进入任意一个下级演示页面再返回的时候，GridViewController总是往上抖动一下

**Comment by MoLice** [comment]
系统 bug，已在 QMUI 4.1.2 修复，具体请查看 https://github.com/Tencent/QMUI_iOS/issues/934 。
