### ISSUE TITLE
真机安装失败。

### ISSUE THREAD

**Issue by ghost** [QMUI/QMUIDemo_iOS#47]
### 运行环境 ###

- [x] iOS 设备：`iPhone XR`
- [x] 系统版本：`iOS 13.3.1`
- [x] Xcode 版本：`11.3.1`
- [x] QMUI iOS 版本：`2020-03-13 github上的版本`

### 具体问题描述 ###
真机安装失败，模拟器可以，网上搜了很多都没有解决。刚接触iOS，还不太懂。

#### 问题截图 ####
dyld: Library not loaded: @rpath/QMUIKit.framework/QMUIKit
  Referenced from: /private/var/containers/Bundle/Application/71A779ED-EB88-4020-B0AC-02864D41385D/qmuidemo.app/qmuidemo
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/71A779ED-EB88-4020-B0AC-02864D41385D/qmuidemo.app/Frameworks/QMUIKit.framework/QMUIKit: code signature invalid for '/private/var/containers/Bundle/Application/71A779ED-EB88-4020-B0AC-02864D41385D/qmuidemo.app/Frameworks/QMUIKit.framework/QMUIKit'

(lldb)

**Comment by MoLice** [comment]
真机编译要有符合要求的证书才可以，你可以了解一下证书相关知识。
