### ISSUE TITLE
'CGRectApplyAffineTransformWithAnchorPoint' has different definitions in different modules; definition in module 'QMUIKit.QMUICommonDefines' first difference is function body

### ISSUE THREAD

**Issue by 1510872953** [QMUI/QMUIDemo_iOS#48]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.x.x`

### 具体问题描述 ###
导入这个框架就会这样

**Comment by MoLice** [comment]
无法重现，请具体说明导入方式，或者提供一份 Demo 项目。

另外，QMUI 的 issue 请提到 [https://github.com/Tencent/QMUI_iOS](https://github.com/Tencent/QMUI_iOS/)，这里是 Demo 的仓库。
