### ISSUE TITLE
使用QMUINavigationController后，可以继续使用系统默认的导航条样式吗

### ISSUE THREAD

**Issue by github641** [QMUI/QMUIDemo_iOS#49]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.3`
- [x] Xcode 版本：`11.3`
- [x] QMUI iOS 版本：`4.0.0`

### 具体问题描述 ###
使用了QMUINavigationController，看了demo中各种主题的切换，效果都很好。目前是想让app处于某个主题下，比如“Pink Rose”，然后保留系统的导航条样式，找了好久也没有发现要怎么设置才能做到，也不知道哪里可以获得咨询和帮助，在这里发个issue请教下。

在QMUIConfigurationTemplate设置 QMUICMI.navBarBackgroundImage为白色，或者是nil都不是系统的bar样式,而且切换时，有闪动的灰黑色过渡动画。

#### 问题截图 ####

![截屏2020-04-23 下午4 23 32](https://user-images.githubusercontent.com/11991492/80076446-cc689180-857e-11ea-8310-62c0bb377b70.png)

**Comment by github641** [comment]
发现将naviBar设置为默认样式，push和pop第一个层级时，导航条的右侧会有，闪动的灰黑色过渡动画，后面的层级就不会出现了

**Comment by github641** [comment]
附上录屏
![Jietu20200426-091740-HD](https://user-images.githubusercontent.com/11991492/80294790-d2d55400-879e-11ea-8993-86c3a9db4249.gif)

**Comment by MoLice** [comment]
系统默认表现就是这样，与 QMUI 无关，你可以写一个空项目测试，在 UITabBarController 里放 UINavigationController 即可。
<img src="https://user-images.githubusercontent.com/1190261/80421355-ebfd1280-890e-11ea-99fb-9e08dcad3a55.png" width="400" />

**Comment by MoLice** [comment]
> 目前是想让app处于某个主题下，比如“Pink Rose”，然后保留系统的导航条样式，找了好久也没有发现要怎么设置才能做到

你的描述说明你使用了配置表，那直接在对应的配置表里修改 NavigationBar 相关的配置即可。如果只是某个界面想要自定义，不跟随全局配置表的样式，则请查看 `QMUINavigationControllerAppearanceDelegate` 接口，直接搜索其中的方法看 QMUI Demo 里是怎么用的就行了。
<img src="https://user-images.githubusercontent.com/1190261/80421998-f66bdc00-890f-11ea-9e4a-8591bfa3859a.png" width="280" /><img src="https://user-images.githubusercontent.com/1190261/80422021-fff54400-890f-11ea-8b69-a717ece33d95.png" width="280" />
