### ISSUE TITLE
statusbar被隐藏

### ISSUE THREAD

**Issue by zephoon** [QMUI/QMUIDemo_iOS#5]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.12.2`
- [x] Xcode 版本：`8.2`
- [x] QMUI iOS 版本：`1.0`

### 具体问题描述 ###
present 一个viewcontroller，之后dismiss返回原先页面，出现statusbar被隐藏
#### 问题截图 ####
<img width="311" alt="1" src="https://cloud.githubusercontent.com/assets/4590967/21748132/b7cf2268-d5b7-11e6-9441-9b9f735a7a22.png">
<img width="311" alt="2" src="https://cloud.githubusercontent.com/assets/4590967/21748133/b836f76c-d5b7-11e6-970f-080a48b79eb1.png">
<img width="311" alt="3" src="https://cloud.githubusercontent.com/assets/4590967/21748134/b837531a-d5b7-11e6-950f-f6ff67a949fb.png">

**Comment by MoLice** [comment]
你好，能否确定这个现象是否因为使用了 QMUI 而导致的？

单纯观察截图来看，直接原因是 `UINavigationBar` 的 `frame` 错误。如需定位问题所在，建议用 swizzling 方式重写 `UINavigationBar` 的 `setFrame:` 方法，或者使用自定义的 `XxNavigationBar`，然后重写 `setFrame:` 方法。在 `setFrame:` 里打断点，看是什么触发了 bar 的高度变化。

**Comment by zephoon** [comment]
那个搜索页面我是使用PYsearch这个第三方库，套了QMUINavigationController， 首页那里也是套了QMUINavigationController，dismiss之后的navbar高度就缩小了（大概是去掉了状态栏的高度）。假如首页那里套原生UINavigationController就没问题。现在我在dismiss之后给首页UINavigationBar 的 setFrame高度加状态栏高度就算是恢复到正常高度了。

**Comment by MoLice** [comment]
嗯，关键是你能看到什么引发了 navigationBar.frame 的变化吗？

**Comment by zephoon** [comment]
估计PYSearch和你们的UI有冲突

**Comment by zephoon** [comment]
具体哪里有问题我也不清楚

**Comment by hi-guy** [comment]
我用的`PYSearch 0.5.5` ，点击`cancel`后没有出现你这个问题
