### ISSUE TITLE
使用导航栏自定义样式问题

### ISSUE THREAD

**Issue by YY873267521** [QMUI/QMUIDemo_iOS#50]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 13.4`
- [x] Xcode 版本：`11.4`
- [x] QMUI iOS 版本：`4.0.0`

### 具体问题描述 ###
使用导航栏自定义样式时，回到主界面再次进入应用，导航栏样式自动切换回当前主题样式。

**Comment by YY873267521** [comment]
![WechatIMG222](https://user-images.githubusercontent.com/45779371/80173368-25d5cc80-8622-11ea-87bc-fdaac3b0b11d.jpeg)

**Comment by MoLice** [comment]
由 https://github.com/Tencent/QMUI_iOS/issues/839 跟进。
