### ISSUE TITLE
关于引用FlexLib布局

### ISSUE THREAD

**Issue by milletpeak** [QMUI/QMUIDemo_iOS#51]
### 运行环境 ###

- [x] iOS 设备：`iPhone XS MAX``
- [x] 系统版本：`iOS Bate 14.1`
- [x] Xcode 版本：`11.5`
- [x] QMUI iOS 版本：`4.1.3`

### 具体问题描述 ###
刚开始使用QMUI，发现QMUICommonViewController与FlexLib中的FlexBaseVC都需要做为项目基类，但Object-C又不支持多继承，这种情况该怎么处理？

**Comment by MoLice** [comment]
没有办法，二选一。
