### ISSUE TITLE
请问可以动态修改字体大小吗

### ISSUE THREAD

**Issue by Wuou** [QMUI/QMUIDemo_iOS#53]
请问可以动态修改字体大小吗

**Comment by MoLice** [comment]
<img src="https://user-images.githubusercontent.com/1190261/95950866-e5644800-0e27-11eb-8ac2-ba7921a448ca.png" width="320" />

<img src="https://user-images.githubusercontent.com/1190261/95950879-ebf2bf80-0e27-11eb-87e8-7c2f960e916f.png" width="320" />

**Comment by Wuou** [comment]
不是跟随系统设置，自定义的。这个框架能实现微信这种调整字体大小效果吗？ 字体变大 相应的UI样式也会跟着变化------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;MoLice&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年10月14日(星期三) 下午2:17
收件人:&nbsp;&quot;QMUI/QMUIDemo_iOS&quot;<QMUIDemo_iOS@noreply.github.com&gt;;
抄送:&nbsp;&quot;Wuou&quot;<352949555@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [QMUI/QMUIDemo_iOS] 请问可以动态修改字体大小吗 (#53)

**Comment by Wuou** [comment]
@MoLice   不是跟随系统设置，自定义的。这个框架能实现微信这种调整字体大小效果吗？ 字体变大 相应的UI样式也会跟着变化
![2081602662729_ pic](https://user-images.githubusercontent.com/14285500/95961089-2c0d6e80-0e37-11eb-806b-9512d4da11a7.jpg)

**Comment by MoLice** [comment]
这其实是一样的，你自己维护一个字号大小级别的数组，然后每次都根据那个数组去加减，得到最终的字号就行了。
这种功能的主要工作量并不是如何实现这个字号的变化，而是每个界面要主动去响应这个变化，那个并不是这种组件能解决的事情。所以你可以先看看我截图的那些相关代码，如果没有使用价值的话，建议自行实现，成本不大。

**Comment by Wuou** [comment]
@MoLice  好的 感谢回答 😁
