### ISSUE TITLE
6s真机运行报错

### ISSUE THREAD

**Issue by zzzzzpppp** [QMUI/QMUIDemo_iOS#54]
### 运行环境 ###

- [x] iOS 设备：`iPhone 6s`
- [x] 系统版本：`iOS 14`
- [x] Xcode 版本：`12.0.1 `
- [x] QMUI iOS 版本：`4.2.0`

### 具体问题描述 ###
手机6s 运行，打开某一个页面，报错，xr就不会
好像是这句
currentViewController.navigationItem.backButtonDisplayMode = UINavigationItemBackButtonDisplayModeMinimal;

#### 问题截图 ####
![QQ20201015-102549@2x](https://user-images.githubusercontent.com/62194012/96069739-63c8f480-0ed1-11eb-9c81-cbf061d1b0ee.jpg)
![QQ20201015-102637@2x](https://user-images.githubusercontent.com/62194012/96069748-675c7b80-0ed1-11eb-80df-661b0dc434d2.jpg)

**Comment by MoLice** [comment]
你的 6s 运行的是早期 iOS 14 Beta 版本吧，这个 API 官方在 Beta3 才增加的。正式版发布后，旧 Beta 版本的问题均不处理。
