### ISSUE TITLE
使用默认的QMUITableViewCell，设置detailTextLabel textLabel 的宽度不生效

### ISSUE THREAD

**Issue by nouslove** [QMUI/QMUIDemo_iOS#55]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.x.x`

**Comment by MoLice** [comment]
issue 信息太不完整了，设置宽度的写法是怎样的？在什么时机？这些都是重要信息，然而没有提供...补充详细后再 open issue。
另外 QMUI 版本是 1.x.x 过于老旧，没有 debug 的价值了，如果因为旧版本的问题导致的，也无法修复。
以及，QMUI 的问题请到 QMUI 仓库提 issue，这是 Demo 的仓库。
