### ISSUE TITLE
tabBarItemTitleFont属性没有对Selected状态无效

### ISSUE THREAD

**Issue by KKWONG1990** [QMUI/QMUIDemo_iOS#56]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 13.5`
- [x] Xcode 版本：`11.5`
- [x] QMUI iOS 版本：`4.1.3`

### 具体问题描述 ###
通过QMUIConfiguration配置表设置tabBarItemTitleFont只能设置normal状态，selected状态无效，导致字体一大一小
#### 问题截图 ####
![Simulator Screen Shot - iPhone 8 - 2020-12-17 at 14 55 01](https://user-images.githubusercontent.com/7710787/102453995-371f8d80-4078-11eb-91c6-d7cfa06df6c5.png)
![1608188146917](https://user-images.githubusercontent.com/7710787/102454016-40105f00-4078-11eb-9482-8610e20fb209.jpg)

**Comment by MoLice** [comment]
![image](https://user-images.githubusercontent.com/1190261/102454431-f8d69e00-4078-11eb-8b60-bb51a3e481d6.png)
即将发布的新版本会新增一个 TabBarItemTitleColorSelected 的配置项用于设置选中状态的 font，请关注新版本发布。

另外 QMUI 的 issue 请提到 QMUI 的 repo，当前 repo 只接受与 QMUI Demo 相关的 issue。
