### ISSUE TITLE
QMUIConsole 在iPad中 按钮不响应

### ISSUE THREAD

**Issue by JzwOnly** [QMUI/QMUIDemo_iOS#57]
### 运行环境 ###

- [x] iOS 设备：`iPad` / `模拟器`
- [x] 系统版本：`iOS 11.5`
- [x] Xcode 版本：`13.5`
- [x] QMUI iOS 版本：`4.2.1`

### 具体问题描述 ###
在iPad中模拟器和真机都有这个问题 iPhone中正常
复现：Demo中 Components->QMUIConsole->打印一条日志 无法返回 主windows被遮挡
qmui_hitTestBlock iPad上 originalView和weakSelf.consoleWindow对象不一致

iPad
(lldb) po weakSelf.consoleWindow
<UIWindow: 0x10781fc50; frame = (0 0; 1024 1366); gestureRecognizers = <NSArray: 0x280e4cde0>; layer = <UIWindowLayer: 0x2800e67e0>>
(lldb) po originalView
<UIView: 0x1054af2f0; frame = (0 0; 1024 1366); clipsToBounds = YES; autoresize = W+H; layer = <CALayer: 0x28000bdc0>>

iPhone
(lldb) po weakSelf.consoleWindow
<UIWindow: 0x154b0f420; frame = (0 0; 375 812); gestureRecognizers = <NSArray: 0x281a7bba0>; layer = <UIWindowLayer: 0x28148b860>>
(lldb) po originalView
<UIWindow: 0x154b0f420; frame = (0 0; 375 812); gestureRecognizers = <NSArray: 0x281a7bba0>; layer = <UIWindowLayer: 0x28148b860>>

**Comment by MoLice** [comment]
https://github.com/Tencent/QMUI_iOS/issues/1169#issuecomment-749403883

在这里已经回应你了，如果仍有问题，请补充其他必要的信息，而不是新开一个一模一样的 issue。

**Comment by JzwOnly** [comment]
@MoLice  十分抱歉  之前的issue没注意到
目前问题：
可能和iPad屏幕尺寸有关  录屏使用的9.7-inch模拟器我测试了没有问题
问题出现在12.0-inch   测试设备：(12.9-inch)(3rd generation)(13.5) 下面是录屏 麻烦再核查一下

https://user-images.githubusercontent.com/21191349/103251533-03b3fb80-49b4-11eb-8b46-25ebc97eac47.mov

**Comment by JzwOnly** [comment]
@MoLice  您好 请问这个问题 又复现吗 该如何处理

**Comment by MoLice** [comment]
已发布 [4.2.2](https://github.com/Tencent/QMUI_iOS/releases/tag/4.2.2) 修复该问题。
