### ISSUE TITLE
ViewController Orientation 在iPad上 修改supportedOrientationMask 设备方向没有被旋转

### ISSUE THREAD

**Issue by JzwOnly** [QMUI/QMUIDemo_iOS#58]
### 运行环境 ###

- [x] iOS 设备：`iPad`
- [x] 系统版本：`iOS 13.5.1`
- [x] Xcode 版本：`11.5`
- [x] QMUI iOS 版本：`4.2.2`

### 具体问题描述 ###
iPad横屏进入 QMUIKit=>ViewController Orientation 修改下个页面支持的方向只支持Portrait  任然横屏 
#### 问题截图 ####
![WechatIMG19](https://user-images.githubusercontent.com/21191349/104299953-cd709300-5500-11eb-95ad-625fed3a7ba4.jpeg)

**Comment by MoLice** [comment]
iPad 天生不支持指定方向
