### ISSUE TITLE
适配版本变了注意改下文档哦

### ISSUE THREAD

**Issue by amoylong** [QMUI/QMUIDemo_iOS#61]
一直pod不下来4.2.2版本的,以为是我pod库更新有问题
后面查看demo的. podspec文件,发现已经适配版本最低改成10.0啦
希望对有此问题的朋友有帮助

**Comment by MoLice** [comment]
![image](https://user-images.githubusercontent.com/1190261/110939833-f9798a80-8370-11eb-8eaf-c19417725868.png)

![image](https://user-images.githubusercontent.com/1190261/110939919-144bff00-8371-11eb-8c5c-18193313153d.png)
