### ISSUE TITLE
framework not found LookinServer

### ISSUE THREAD

**Issue by NicholasBxt** [QMUI/QMUIDemo_iOS#62]
### 运行环境 ###

- [x] iOS 设备：`iPad`   模拟器`
- [x] 系统版本：`iOS 11.2.3`
- [x] Xcode 版本：`12.4`
- [x] QMUI iOS 版本：`4.2.3`

### 具体问题描述 ###
ld: framework not found LookinServer
clang: error: linker command failed with exit code 1 (use -v to see invocation)
#### 问题截图 ####
<img width="846" alt="WX20210408-105336@2x" src="https://user-images.githubusercontent.com/12780456/113961489-bb309780-9858-11eb-9ce3-1f6b4629ab0b.png">

**Comment by NicholasBxt** [comment]
![1617851343103](https://user-images.githubusercontent.com/12780456/113962784-f207ad00-985a-11eb-8d0f-5e3474f527e6.jpg)

**Comment by NicholasBxt** [comment]
已解决，因为目录有中文😂

**Comment by leeberlin** [comment]
how you can get lookinserver.framework ?

**Comment by MoLice** [comment]
> how you can get lookinserver.framework ?

@leeberlin https://lookin.work/faq/integration-manual/

**Comment by leeberlin** [comment]
@MoLice  do you have any social Network ? Want to asking about Monkeydev with Lookin . Thanks broo
