### ISSUE TITLE
XCode11新创建的项目下调用+ (nullable UIViewController *)visibleViewController方法会闪退

### ISSUE THREAD

**Issue by jgyhc** [QMUI/QMUIDemo_iOS#63]
### 运行环境 ###

- [x] iOS 设备：`iPhone`
- [x] 系统版本：`iOS 14.1`
- [x] Xcode 版本：`11.0`
- [x] QMUI iOS 版本：`4.2.3`

### 具体问题描述 ###
XCode11新创建的项目里是有`SceneDelegate `文件的，UI生命周期交给`SceneDelegate`处理了，所以在QMUI项目下文件`UIViewController+QMUI`中的方法:
```
+ (nullable UIViewController *)visibleViewController {
    UIViewController *rootViewController = UIApplication.sharedApplication.delegate.window.rootViewController;
    UIViewController *visibleViewController = [rootViewController qmui_visibleViewControllerIfExist];
    return visibleViewController;
}

```

其中`UIApplication.sharedApplication.delegate`就不能取到对应的`window`属性了。
希望可以兼容一下这种情况。

**Comment by MoLice** [comment]
请查看：https://github.com/Tencent/QMUI_iOS/issues/766

另外 QMUI 的 issue 请提到 QMUI 的 repo 里，这里是 Demo 的。
