### ISSUE TITLE
无法使用 UITabBarItem setTitleTextAttributes 修改样式

### ISSUE THREAD

**Issue by qingweiSun** [QMUI/QMUIDemo_iOS#65]
### 运行环境 ###

- [x] iOS 设备：iPhone
- [x] 系统版本：iOS 14.7.1
- [x] Xcode 版本：12.5.1
- [x] QMUI iOS 版本：4.2.3

### 具体问题描述 ###
不管是 qmui 的 UITabBarController 还是原生的 UITabBarController tabBar 的富文本属性都失效了
 // 修改标签栏选中时文字颜色
      viewController.tabBarItem.setTitleTextAttributes(
          [NSAttributedString.Key.foregroundColor: UIColor.init(valueRGB: 0xFF7F7F7F),
           NSAttributedString.Key.font: UIFont.boldSystemFont(ofSize: 11)], for: .normal)
      // 修改标签栏未选中时文字颜色
      viewController.tabBarItem.setTitleTextAttributes(
          [NSAttributedString.Key.foregroundColor: UIColor.init(valueRGB: 0xFF567AFF),
           NSAttributedString.Key.font: UIFont.boldSystemFont(ofSize: 11)], for: .selected)
    }
颜色无法修改

**Comment by MoLice** [comment]
**QMUI 的问题请到 QMUI 的 GitHub 去提 issue，这里是 Demo 的。**

系统在 iOS 13 开始新增了 `UIBarAppearance` 系列的 Class 专门用于设置 `UINavigationBar`、`UIToolbar`、`UITabBar` 的样式，新 API 与你 issue 里提的旧 API 是互相冲突的，只要项目里用了新 API，所有旧 API 都无效（或部分有效）。

QMUI 在 iOS 13 及以上用了新 API 来解决系统的某些 Bug（具体可查看 [QMUI 4.0.0 Release Note](https://github.com/Tencent/QMUI_iOS/releases/tag/4.0.0)，或者 #618）。
<img src="https://user-images.githubusercontent.com/1190261/129520090-f0acf656-d8be-4e11-8dfb-9057fa343459.png" width="600" />

但对于 UITabBarItem 的接口，QMUI 难以自动将旧 API 映射到新 API，所以没有处理。所以对业务项目而言，需要自行判断 iOS 版本，用不同的方式去设置样式。对应你的需求，建议首选通过配置表去设置全局的 UITabBarItem 样式，如果不希望用配置表，也可参考下方代码实现：
```
if (@available(iOS 13.0, *)) {
    [self.tabBarController.tabBar.standardAppearance qmui_applyItemAppearanceWithBlock:^(UITabBarItemAppearance * _Nonnull itemAppearance) {
        itemAppearance.normal.titleTextAttributes = xxx;
        itemAppearance.selected.titleTextAttributes = xxx;
    }];
} else {
    // 旧写法
}
```
