### ISSUE TITLE
ios15 导航栏默认变成了白色

### ISSUE THREAD

**Issue by svweb** [QMUI/QMUIDemo_iOS#66]
### 运行环境 ###
xcode 13.0

- [x] iOS 设备 `iphone 12,iphone 13 模拟器`
- [x] 系统版本：`iOS 15.0`
- [x] Xcode 版本：`13.x`
- [x] QMUI iOS 版本：`4.3.0`

### 具体问题描述 ###

导航栏默认只有白色，没有主题色,滚动下面的列表时可以显示主题色

#### 问题截图 ####
![Snipaste_2021-09-15_11-21-31](https://user-images.githubusercontent.com/46740229/133365290-0debd313-8f2d-49bc-8c82-db706bf0426b.jpg)

**Comment by MoLice** [comment]
https://github.com/Tencent/QMUI_iOS/issues/1265
