### ISSUE TITLE
Xcode 13 + iOS15 导航栏白色

### ISSUE THREAD

**Issue by TimorCan** [QMUI/QMUIDemo_iOS#67]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 15`
- [x] Xcode 版本：`Xcode 13`
- [x] QMUI iOS 版本：`4.3.0`

### 具体问题描述 ###
   导航栏出现白色，demo的导航栏也是白色
#### 问题截图 ###
![486E06D995CBDE6652503E67A9490901](https://user-images.githubusercontent.com/10477210/134600245-be701a50-eff2-4683-b871-1a94b1426dce.png)
![3F06AE4E7CD84FAB16E2FD083FDD58AC](https://user-images.githubusercontent.com/10477210/134600252-9dc2419c-cec4-49cd-a3c5-2b60bb89bb23.png)
#

**Comment by daiyuandbaby** [comment]
我也在iOS15遇到这个问题，等待解决

**Comment by MoLice** [comment]
https://github.com/Tencent/QMUI_iOS/issues/1265
