### ISSUE TITLE
QMUISlider没啥用，不如用自定义UIView + 手势替换？这样扩展性高，实用性更强，QMUISlider就像棉裤套了个皮裤😂

### ISSUE THREAD

**Issue by NicholasBxt** [QMUI/QMUIDemo_iOS#69]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.x.x`

**Comment by MoLice** [comment]
系统改了 UISlider，QMUISlider 也会跟着变，项目里做 isKindfOfClass 之类的操作时也可以用系统的 UISlider.class 通吃，这就是和自定义 UIView 的区别。
