### ISSUE TITLE
请问有用虚线框来裁剪图片的功能吗

### ISSUE THREAD

**Issue by songxing10000** [QMUI/QMUIDemo_iOS#7]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.x.x`

**Comment by MoLice** [comment]
你的意思是否等价于裁剪图片后给图片加上虚线边框？如果要给图片加虚线边框，请参考 [UIImage (QMUI)](https://github.com/QMUI/QMUI_iOS/blob/master/QMUIKit/UIKitExtensions/UIImage%2BQMUI.h#L130-L141)

**Comment by songxing10000** [comment]
是从相册选取一张照片时进行裁剪，要用虚线裁剪

**Comment by MoLice** [comment]
目前暂时没有，需要的话得由业务自行实现哈。
