### ISSUE TITLE
iOS15 在使用QMUIAlertController的时候崩溃

### ISSUE THREAD

**Issue by LiFuPeng** [QMUI/QMUIDemo_iOS#70]
### 运行环境 ###

- [x] iOS 设备：`iPhone` --- `模拟器`
- [x] 系统版本：`iOS 15`
- [x] Xcode 版本：`13.1`
- [x] QMUI iOS 版本：`1.x.x`

### 具体问题描述 ###

在使用QMUIAlertController的时候，调用- (void)showWithAnimated:(BOOL)animated{}函数，会崩溃，崩溃的函数：
+ (nullable UIViewController *)visibleViewController {
    UIViewController *rootViewController = UIApplication.sharedApplication.delegate.window.rootViewController;
    UIViewController *visibleViewController = [rootViewController qmui_visibleViewControllerIfExist];
    return visibleViewController;
}

崩溃信息如下：
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001803e10e8 __exceptionPreprocess + 236
	1   libobjc.A.dylib                     0x0000000180193384 objc_exception_throw + 56
	2   CoreFoundation                      0x00000001803f0480 +[NSObject(NSObject) instanceMethodSignatureForSelector:] + 0
	3   UIKitCore                           0x0000000184d70c80 -[UIResponder doesNotRecognizeSelector:] + 268
	4   CoreFoundation                      0x00000001803e5098 ___forwarding___ + 700
	5   CoreFoundation                      0x00000001803e738c _CF_forwarding_prep_0 + 92
	6   QMUIKit                             0x00000001018f5f48 +[QMUIHelper(ViewController) visibleViewController] + 88
	7   QMUIKit                             0x0000000101806dcc -[QMUIModalPresentationViewController didInitialize] + 120
	8   QMUIKit                             0x0000000101806c40 -[QMUIModalPresentationViewController initWithNibName:bundle:] + 160
	9   QMUIKit                             0x0000000101771c34 -[QMUIAlertController initModalPresentationController] + 44
	10  QMUIKit                             0x0000000101773370 -[QMUIAlertController showWithAnimated:] + 380
	11  TestSwift                           0x0000000100da10e8 $s9TestSwift14ViewControllerC1byySo8UIButtonCF + 816
	12  TestSwift                           0x0000000100da13e4 $s9TestSwift14ViewControllerC1byySo8UIButtonCFTo + 52
	13  UIKitCore                           0x0000000184d416b4 -[UIApplication sendAction:to:from:forEvent:] + 96
	14  UIKitCore                           0x0000000184645a4c -[UIControl sendAction:to:forEvent:] + 124
	15  UIKitCore                           0x0000000184645e30 -[UIControl _sendActionsForEvents:withEvent:] + 348
	16  UIKitCore                           0x00000001846422a4 -[UIButton _sendActionsForEvents:withEvent:] + 156
	17  UIKitCore                           0x0000000184644768 -[UIControl touchesEnded:withEvent:] + 532
	18  UIKitCore                           0x0000000184d7f840 -[UIWindow _sendTouchesForEvent:] + 1104
	19  UIKitCore                           0x0000000184d81338 -[UIWindow sendEvent:] + 4352
	20  UIKitCore                           0x0000000184d598cc -[UIApplication sendEvent:] + 788
	21  UIKitCore                           0x0000000184de5b44 __dispatchPreprocessedEventFromEventQueue + 7576
	22  UIKitCore                           0x0000000184de7bd8 __processEventQueue + 6792
	23  UIKitCore                           0x0000000184ddfbb4 __eventFetcherSourceCallback + 184
	24  CoreFoundation                      0x0000000180350220 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
	25  CoreFoundation                      0x0000000180350128 __CFRunLoopDoSource0 + 200
	26  CoreFoundation                      0x000000018034f4b4 __CFRunLoopDoSources0 + 256
	27  CoreFoundation                      0x0000000180349afc __CFRunLoopRun + 744
	28  CoreFoundation                      0x0000000180349308 CFRunLoopRunSpecific + 572
	29  GraphicsServices                    0x000000018bf025ec GSEventRunModal + 160
	30  UIKitCore                           0x0000000184d3b4e0 -[UIApplication _run] + 992
	31  UIKitCore                           0x0000000184d3ffc0 UIApplicationMain + 112
	32  libswiftUIKit.dylib                 0x00000001b5f7d104 $s5UIKit17UIApplicationMainys5Int32VAD_SpySpys4Int8VGGSgSSSgAJtF + 100
	33  TestSwift                           0x0000000100da2150 $sSo21UIApplicationDelegateP5UIKitE4mainyyFZ + 104
	34  TestSwift                           0x0000000100da20d8 $s9TestSwift11AppDelegateC5$mainyyFZ + 44
	35  TestSwift                           0x0000000100da21d0 main + 28
	36  dyld                                0x0000000100dd9c04 start_sim + 20
	37  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi: terminating with uncaught exception of type NSException
dyld4 config: DYLD_ROOT_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot DYLD_LIBRARY_PATH=/Users/jingzhuan/Library/Developer/Xcode/DerivedData/TestSwift-aphtaijzqgnrhdamoiavqonvmogc/Build/Products/Debug-iphonesimulator:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libBacktraceRecording.dylib:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libMainThreadChecker.dylib:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib DYLD_FRAMEWORK_PATH=/Users/jingzhuan/Library/Developer/Xcode/DerivedData/TestSwift-aphtaijzqgnrhdamoiavqonvmogc/Build/Products/Debug-iphonesimulator
terminating with uncaught exception of type NSException
CoreSimulator 776.4 - Device: iPhone 13 (085E39D8-EFAA-49E8-96FA-49B5D1AACE71) - Runtime: iOS 15.0 (19A339) - DeviceType: iPhone 13
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[TestSwift.AppDelegate window]: unrecognized selector sent to instance 0x60000152c330'

**Comment by MoLice** [comment]
QMUI 的问题请到 QMUI 的 repo 提 issue，这里是 QMUI Demo 的。
https://github.com/Tencent/QMUI_iOS/issues/766
