### ISSUE TITLE
导入 QMUIConfigurationTemplate 文件夹，程序不能正常运行

### ISSUE THREAD

**Issue by jingyu982887078** [QMUI/QMUIDemo_iOS#72]
### 运行环境 ###

- [x] iOS 设备：`iPhone` / `iPad` / `模拟器`
- [x] 系统版本：`iOS 10.x`
- [x] Xcode 版本：`8.x`
- [x] QMUI iOS 版本：`1.x.x`

**Comment by jingyu982887078** [comment]
<img width="853" alt="image" src="https://user-images.githubusercontent.com/19472151/154896749-1c2b6c9e-026a-422c-a873-b5f5c2a74da1.png">

**Comment by MoLice** [comment]
1.x 的版本不处理。
![image](https://user-images.githubusercontent.com/1190261/154901071-137cb4d3-ebbd-4fe9-ab71-a4630c09727b.png)
