### ISSUE TITLE
QMUITableViewStyleInsetGrouped的阴影设置

### ISSUE THREAD

**Issue by machengshuai92** [QMUI/QMUIDemo_iOS#74]
### 运行环境 ###

- [x] iOS 设备：`iPhone`
- [x] 系统版本：`iOS 15.1`
- [x] Xcode 版本：`13.4`
- [x] QMUI iOS 版本：`4.4.3`

### 具体问题描述 ###
您好,是否可以增加Tableview在"QMUITableViewStyleInsetGrouped"style下包围section的背景的阴影设置..感谢..

**Comment by MoLice** [comment]
系统应该也不支持吧？如果有这种诉求，目前比较好的实现方式是用 UICollectionView，它可以用 decoration 来实现，比 tableView 优雅很多。

**Comment by machengshuai92** [comment]
thx
