### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code -- 编译不通过

### ISSUE THREAD

**Issue by zj381652512** [QMUI/QMUIDemo_iOS#76]
### 运行环境 ###

- [x] iOS 设备：iPhoneSE2()
- [x] 系统版本：iOS15.4.1
- [x] Xcode 版本：13.2.1
- [x] QMUI iOS 版本：4.4.2(17)

### 具体问题描述 ###

编译不通过

/bin/sh: /Users/sword/Library/Developer/Xcode/DerivedData/qmuidemo-hewcidelsdcjwphggyuufnwrsuwl/Build/Intermediates.noindex/qmui.build/Debug-iphoneos/QMUIKit.build/Script-CDE38A6F1F70F745001ACF2C.sh: /usr/bin/python: bad interpreter: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code

#### 问题截图 ####

<img width="1443" alt="截屏2022-07-25 20 26 29" src="https://user-images.githubusercontent.com/17876394/180777136-eeea5412-c120-47d4-bc6b-23bf8cde2da8.png">

**Comment by Nuyaij-c** [comment]
#73 这个issue里已经解决了

**Comment by Nuyaij-c** [comment]
#73 这个issue里已经解决了

**Comment by yjgfn** [comment]
#77 
这里可以修改为自己安装的python path，完美解决
<img width="1023" alt="Snipaste_2022-08-04_12-49-05" src="https://user-images.githubusercontent.com/6059423/182766056-1e1417d7-3849-4c23-aebc-0bcb102b29ce.png">

**Comment by MoLice** [comment]
已更新 4.5.0 修复该问题。
