### ISSUE TITLE
太棒了，绝妙的方法，搞定

### ISSUE THREAD

**Issue by iihe602** [QMUI/QMUIDemo_iOS#77]
> > > <img alt="图片" width="303" src="https://user-images.githubusercontent.com/9424775/159481069-c2eb8331-acb0-4201-a97a-66b56f178fb2.png">
> > > 最新版的macOS干掉了Python2的支持，把这两个地方改成Python3就可以了
> > 
> > 
> > 兄弟怎么搜索到的，能写清楚点吗？我只能找到umbrellaHeaderFileCreator 文件里面的python 你用什么工具搜索的？
> 
> 用vscode打开搜索python

厉害啊 亲测有效

_Originally posted by @Celia-Jiang in https://github.com/QMUI/QMUIDemo_iOS/issues/73#issuecomment-1124575820_

**Comment by diors886** [comment]
它这个demo怎么连入口文件都没，只有框架的东西...

**Comment by yjgfn** [comment]
#76 
这里可以直接设置
<img width="1023" alt="Snipaste_2022-08-04_12-49-05" src="https://user-images.githubusercontent.com/6059423/182766173-c901f8b2-4217-4a61-93c8-663a5f1108a6.png">

**Comment by diors886** [comment]
这demo导航栏都没适配一下....😹

**Comment by MoLice** [comment]
> 这demo导航栏都没适配一下....😹

@shmchen iOS 15 跑起来是这样，你具体是指怎么个没适配法？

<img width="451" alt="image" src="https://user-images.githubusercontent.com/1190261/182858722-8cc4d674-a954-4ea9-845c-9257945327c2.png">

**Comment by shmchen** [comment]
>
我这边跑起来是这个样子的 
![WX20220808-092526](https://user-images.githubusercontent.com/13509756/183321017-6fc0fff9-ae5a-4686-a8a8-6349415fa555.png)

**Comment by diors886** [comment]
> > 这demo导航栏都没适配一下....😹
> 
> @shmchen iOS 15 跑起来是这样，你具体是指怎么个没适配法？
> 
> <img alt="image" width="451" src="https://user-images.githubusercontent.com/1190261/182858722-8cc4d674-a954-4ea9-845c-9257945327c2.png">

现在可以了，之前github太卡，下载很多次都报错，于是从oschina上下载镜像，是4.2.3版本的，以为没适配；重新下载这边最新版本可以了（不懂python，为啥不直接设置成python3...）
![image](https://user-images.githubusercontent.com/13509756/183321103-f1380bd4-e960-44ea-8aff-5d8328ba9de7.png)

**Comment by MoLice** [comment]
> 为啥不直接设置成python3

因为自从 macOS 把内置的 python2 改为 python3 至今，QMUI 还没发过新版本。

**Comment by MoLice** [comment]
已更新 4.5.0 修复该问题。
