### ISSUE TITLE
返回按钮失效，手势返回不灵敏

### ISSUE THREAD

**Issue by XiangHongJiang** [QMUI/QMUIDemo_iOS#79]
### 运行环境 ###

- [x] iOS 设备：`模拟器 iPhone 13` 
- [x] 系统版本：`iOS 15.2`
- [x] Xcode 版本：`13.2.1`
- [x] QMUI iOS 版本：`4.5.0`

### 具体问题描述 ###
···
1. 点击Componets→进入任一类目，有些首次进入返回按钮点击，能正常返回首页，有些无法返回，得通过手势返回。
2. 首页点击任一功能，进入二级页面返回手势不灵敏，有时失效。
···

**Comment by MoLice** [comment]
未发现该问题，请补充其他详细信息再回复。

**Comment by Lucien-H** [comment]
> ### 运行环境
> * [x]  iOS 设备：`模拟器 iPhone 13`
> * [x]  系统版本：`iOS 15.2`
> * [x]  Xcode 版本：`13.2.1`
> * [x]  QMUI iOS 版本：`4.5.0`
> 
> ### 具体问题描述
> ···
> 
> 1. 点击Componets→进入任一类目，有些首次进入返回按钮点击，能正常返回首页，有些无法返回，得通过手势返回。
> 2. 首页点击任一功能，进入二级页面返回手势不灵敏，有时失效。
>    ···
> 
> #### 问题截图

你好，我也出现了和你一样的情况，在M2系列模拟器上运行，你是怎么解决的呢？

**Comment by MoLice** [comment]
参考 https://github.com/Tencent/QMUI_iOS/issues/1466
