### ISSUE TITLE
Dismiss转屏问题

### ISSUE THREAD

**Issue by PeiYanDong** [QMUI/QMUIDemo_iOS#80]
### 运行环境 ###

- [x] iOS 设备：`iPhone` /  `模拟器`
- [x] 系统版本：`iOS 13 ~ 16`
- [x] Xcode 版本：`14.2`
- [x] QMUI iOS 版本：`4.6.3`

### QMUI转屏 由只支持横屏present到只支持竖屏，退出竖屏 界面会先竖屏再横屏，对仅支持横屏展示的界面效果不是很友好 ###

测试定位到QMUINavigationController的supportedInterfaceOrientations方法中visibleViewController会先取到竖屏的VC，再次取到的才是横屏的VC, 这种情况如果直接取self.topViewController就不会有问题

https://user-images.githubusercontent.com/14860893/210312962-c51e187b-7752-46b4-8061-bac5103dc80c.mov

**Comment by MoLice** [comment]
好，我看一下，同时麻烦把 issue 提到 https://github.com/Tencent/QMUI_iOS/issues 那边，这里是 Demo 的。

**Comment by PeiYanDong** [comment]
> 好，我看一下，同时麻烦把 issue 提到 https://github.com/Tencent/QMUI_iOS/issues 那边，这里是 Demo 的。

好的，已经在QMUI_iOS框架那边重新提了一个，这个关掉了
