### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by candyxj123** [QMUI/QMUIDemo_iOS#85]
### 运行环境 ###

- [x] iOS 设备：`iPhone`
- [x] 系统版本：`iOS 18.1`
- [x] Xcode 版本：`16.1`
- [x] QMUI iOS 版本：`4.7.0`

### 具体问题描述 ###
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '如果你看到这条提示，建议到 GitHub 上提 issue，让我们联系你查看项目的配置表使用情况，否则请注释掉这一行。'
*** First throw call stack:
(0x19edf87cc 0x19c0cb2e4 0x19e1c88d8 0x103094180 0x10319aeac 0x101c3671c 0x101c382a0 0x10319a738 0x19c0b8820 0x1c478ed10 0x1c47c7908 0x1c47c78b4 0x1c47c78b4 0x1c47c92c8 0x1c4794c00 0x1c4784280 0x1c4798d10 0x1c47bd9f8 0x1c47b6cb0)
libc++abi: terminating due to uncaught exception of type NSException
*** Assertion failure in -[QMUIConfiguration applyInitialTemplate], QMUIConfiguration.m:101
#### 问题截图 ####
![QQ_1730702538603](https://github.com/user-attachments/assets/c13de5ea-fd7e-437b-9c53-3f55009b653e)

**Comment by MoLice** [comment]
已经存在大量这个重复的 issue，简单搜一下应该就可以解决

**Comment by candyxj123** [comment]
搜索相关的资料，没有看到解决方案

**Comment by MoLice** [comment]
<img width="1224" alt="image" src="https://github.com/user-attachments/assets/e703d65a-3cd2-42ae-908f-68171027572d">
